### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [jamessturges/dalle-mini-buddy#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by jamessturges** [comment]
Added a LICENSE file with AGPL 3.0. Thank you so much, I’m new to the whole OSS thing!

7ea30c841e1ed5a9f3f539361f824a52a0dceed1
